[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
name = "packaging-academy"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build-docs = "mkdocs build --strict"
serve = "mkdocs serve"
deploy-latest = "mike deploy --push --update-aliases $RELEASE_VERSION latest"
deploy-dev = "mike deploy --push dev devel"

[dependencies]
cairosvg = "2.7.1.*"
mike = "2.0.0.*"
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.6.4,<10"
mkdocstrings = ">=0.27.0,<0.28"
mkdocstrings-python = ">=1.13.0,<2"
pillow = ">=9.4.0"
ruff = ">=0.4.10,<0.5"